export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as About} from './About'
export {default as PostList} from './PostList'
export {default as PostDetail} from './PostDetail'
